### ISSUE TITLE
Separate syntax highlighting for piped wikilinks

### ISSUE THREAD

**Issue by uozuAho** [kortina/vscode-markdown-notes#102]
**Is your feature request related to a problem? Please describe.**
I've just discovered this extension, and I find it harder to read the links I've created using the piped wikilink format.

**Describe the solution you'd like**
I'd like the description part of a piped wikilink to be highlighted in the same way regular markdown links are highlighted. Eg.
![image](https://user-images.githubusercontent.com/2265109/95974469-be763800-0e60-11eb-8101-8b9d319fae67.png)

**Describe alternatives you've considered**
No alternatives come to mind, but the workaround I use is to put a space between the description and the pipe, as in the image above. This makes the description slightly easier to see.

**Additional context**
I'm happy to create a PR for this. I just thought I'd raise the idea first before working on it. Let me know if it's already been thought of and/or won't work for some reason. I'll slowly tinker in the meantime.

**Comment by xinbenlv** [comment]
+1. Or even better, leverage what's real Wiki-link format, such as namespace, cross-site etc.
See: https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking#General_points_on_linking_style

**Comment by kortina** [comment]
This would involve a change to the regex here:

https://github.com/kortina/vscode-markdown-notes/blob/master/syntaxes/notes.tmLanguage.json#L7

You can see that this one defines 3 capture groups

```
         "name": "punctuation.definition.wiki-link"
          "name": "support.function.text.markdown.notes.wiki-link.title"
          "name": "punctuation.definition.wiki-link"
```

To implement what you are suggesting, we need to make this also able to parse out the text preceding and succeeding the `|` character into separate capture groups.

It's probably not terribly hard to do this, but you'd need to be really careful to make sure it works for both the case where a pipe character is used and the case where one is not used (you'd just have one null capture group in that case).

Happy to review a PR if you want to test + submit one!

**Comment by uozuAho** [comment]
I can't figure out how to handle the configurable file/description order, eg. how to handle `[[file | description]]` vs. `[[description | file]]`. Perhaps it's enough that the colours of `file` and `description` are different. That way the item on the left would always be red (for example), whether it's a filename or a description. Any thoughts?
