### ISSUE TITLE
How to use a different timestamp format when creating a new note?

### ISSUE THREAD

**Issue by vasko-deb** [kortina/vscode-markdown-notes#103]
This is not a bug per say, but rather a question. I love the extension and use it a lot.

I currently create new notes with the following template:

---\ntitle: "${noteName}"\ndate: "${timestamp}"\ntags:\n---\n# ${noteName}\n

This produces a new note which looks something like:

---
title: "My New Name"
date: "2020-07-09T05:29:00.541Z"
---
# My New Name

I want to truncate the timestamp to just the date and get something like

---
title: "My New Name"
date: "2020-07-09"
---
# My New Name

So my question is what is the syntax to truncate the timestamp when I setup the new note template?

**Comment by kortina** [comment]
I think you are looking for the `${date}` substitution var:

https://github.com/kortina/vscode-markdown-notes/blob/472bd5d3975ba68bf6840a9b767c7d46262abf86/src/NoteWorkspace.ts#L461
