### ISSUE TITLE
Put backlinks in code files

### ISSUE THREAD

**Issue by ThariqS** [kortina/vscode-markdown-notes#106]
**Is your feature request related to a problem? Please describe.**
I want to use markdown-notes in a large codebase, but it's unintuitive to include a .md file for every file we want to document.

**Describe the solution you'd like**
I would really like to be able to create my back links in code such that they could reference markdown documentation.

**Describe alternatives you've considered**
Just making a lot more MD files, but I fear no one will read them.

**Additional context**
N/A

**Comment by digitalsignalperson** [comment]
same as #107 if there is a setting for allowed file extensions (e.g. *.txt, *.cpp, *.h)...

**Comment by kortina** [comment]
Closing in favor of #107
