### ISSUE TITLE
Window Log polluted with: Error: ENOENT: no such file or directory, open 'rendererLog'

### ISSUE THREAD

**Issue by JobJob** [kortina/vscode-markdown-notes#108]
**Describe the bug**
When this extension is enabled, every ~1.5 seconds the `Log (Window)` shows the following: `[error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'`. It stops when this extension is disabled (and the window reloaded).

**To Reproduce**
1. Run the command `Developer: Show Logs...`
2. Choose `Window`
3. See the message printed about every 1.5 seconds

**Expected behavior**
Message not to be printed even once 😄 

**Comments**
This may be the same issue as this: https://github.com/shardulm94/vscode-trailingspaces/issues/22

At a guess from reading [this issue comment](https://github.com/shardulm94/vscode-trailingspaces/issues/22#issuecomment-477882595), and searching their code for `scheme`, maybe you just need to only activate this extension for files where `!document.isUntitled && document.uri.scheme == "file"`

Cheers.

**Comment by kortina** [comment]
Resolved by aee655872041508efa0fc4ed1c01f89a730e24d7
