### ISSUE TITLE
Tag recognition is too tolerant

### ISSUE THREAD

**Issue by frankreporting** [kortina/vscode-markdown-notes#114]
**Describe the bug**
Markdown Notes is recognizing and storing in memory all strings that begin with '#' regardless of whether they represent a distinct word or happen to come at the middle or end of a longer string, such as a URL that includes a heading ID (i.e. `webaddress.com/path-to-page#heading-ID`). If you happen to have a lot of notes with links like this, it clutters the list of stored tags, so it becomes hard to know which IntelliSense suggestions are real tags and which are accidental. 

**To Reproduce**
- Create a note with a link that includes a heading ID like `website.com/this-url-plus#heading`
- In another note, type `#h` and trigger IntelliSense, and you should see "#heading" as an option

**Expected behavior**
Markdown Notes should detect a whitespace character or comma in front of the `#` indicating that it is alone on a line or part of a list of tags. That separator could help it distinguish between a proper tag and a stray "#" character that happens to be in a URL or elsewhere.

**Screenshots**
![Screen Shot 2020-12-28 at 8 37 18 PM](https://user-images.githubusercontent.com/2828254/103259038-915c0080-494c-11eb-9ea5-5c0e66a5fed1.png)

*Above, you can see the list of tags returned for certain strings is so bloated it's almost useless. The vast majority of the items in the list are actually heading-ID's contained in links across my notebook.*

**Versions**
 - OS: [eg macOS 11.1]
 - VS Code Version: [eg 1.52.1]
 - Extension Version: [eg 0.0.21]

**Comment by frankreporting** [comment]
Turns out there may be a simple fix. I have it working, though I don't know yet if there will be any unwanted side effects down the line. 

To fix: 

Add a simple look behind (`(?<= |,|^)`) for commas, spaces, and line beginnings in the regex for `_rxTagNoAnchors` in NoteWorkspace.js

The line is around 468 or so:

```
NoteWorkspace._rxTagNoAnchors = '\\#[\\w\\-\\_]+'; // used to match tags that appear within lines
```

So it will end up looking like this:

```
NoteWorkspace._rxTagNoAnchors = '(?<= |,|^)\\#[\\w\\-\\_]+'; // used to match tags that appear within lines
```

This means it should recognize only `#tags` that are at the start of a line or follow a space or comma, the idea being that you want to eliminate strings where the `#` may be in the middle of other characters, as with heading ID's appended to URL's.

**Comment by thomaskoppelaar** [comment]
I personally agree with implementing this fix - in fact, this was something that was marked as a TODO in extension.test.ts:
```js
    // TODO: should this match or not?
    // expect('[site](http://something/#com).').not.toMatch(rx);
```
I added your regex and ran this test - It passes just fine.


I'll create a draft PR and credit you.

**Comment by kortina** [comment]
Awesome -- will try to merge in these outstanding PRs this weekend. Thank you both.
