### ISSUE TITLE
"Create note on go to definition when missing" shouldn't auto-capitalize words

### ISSUE THREAD

**Issue by mnowotnik** [kortina/vscode-markdown-notes#125]
**Describe the bug**
Creating new note using command `New note` preserves word capitalization. However, creating a note
with exactly the same title using "Create note on go to definition when missing"  causes the words
in the title to become capitalized.

1. Set user settings
```
  "vscodeMarkdownNotes.noteCompletionConvention": "noExtension",
  "vscodeMarkdownNotes.previewLabelStyling": "label",
  "vscodeMarkdownNotes.lowercaseNewNoteFilenames": false,
  "vscodeMarkdownNotes.slugifyMethod": "classic",
  "vscodeMarkdownNotes.createNoteOnGoToDefinitionWhenMissing": true,
  "vscodeMarkdownNotes.slugifyCharacter": "NONE"
```
2. Create wikilink in a note `[[Foo bar baz]]`
3. Follow the link
4. A note is created with title "Foo Bar Baz"

**Expected behavior**
A note with title "Foo bar baz" should be created.

**Comment by kortina** [comment]
I have confirmed this behavior. This is probably quite a simple thing to fix / add some unit tests around, so would be awesome if someone wanted to pick this one up!
