### ISSUE TITLE
Machine specific urls are created for links

### ISSUE THREAD

**Issue by chrisolsen** [kortina/vscode-markdown-notes#136]
**Describe the bug**
Link reference is specific to current machine

**To Reproduce**
- Create a [[link]] and click it

**Expected behavior**
- a file next to the current is created 
- a relative link is created in the link references

**What actually happens**
- a file **is** created
- a link like the following is created `[some-file]: ../../../../../../../c:/Users/Chris/Projects/notes/Learning/ccna/some-file.md "some-file"`

```
[[some-file]]

[//begin]: # "Autogenerated link references for markdown compatibility"
[some-file]: ../../../../../../../c:/Users/Chris/Projects/notes/Learning/ccna/some-file.md "some-file"
[//end]: # "Autogenerated link references"
```

**Versions**
 - OS: windows 10
 - VS Code Version: 1.54.3
 - Extension Version: 0.0.24

**Comment by kortina** [comment]
What setting are you using for `vscodeMarkdownNotes.workspaceFilenameConvention`? `uniqueFilenames` or `relativePaths`? Guessing the latter?

**Comment by chrisolsen** [comment]
I am using the default value of `uniqueFilenames`

**Comment by kortina** [comment]
Oh, that's very strange. I wonder how this is working for any Windows users then...

Is this the full string of text that gets inserted into your document?

```
[some-file]: ../../../../../../../c:/Users/Chris/Projects/notes/Learning/ccna/some-file.md "some-file"
```

Cause really just the `[some-file]` should exist and when you navigate to it it should just open the file in the Workspace root directory.

Any other windows users having the same problem?

I think the relevant code is here and this looks ok to me: https://github.com/kortina/vscode-markdown-notes/blob/master/src/NoteWorkspace.ts#L535

**Comment by chrisolsen** [comment]
I think I had another markdown plugin that was also watching for ctrl-clicks on `[[links]]`. I created some notes in a new folder with the plugin disabled and things are working well now. Sorry for the confusion.
