### ISSUE TITLE
Creating notes with go-to-definition on slug-based links creates new notes with "slug_title", not human readable "Slug Title"

### ISSUE THREAD

**Issue by jli** [kortina/vscode-markdown-notes#149]
**Describe the bug**
My naming conventions: `[[slug_wiki_links]]` in my notes, which link to `slug_wiki_links.md` files, with note titles like `# Slug Wiki Links`.

With `vscodeMarkdownNotes.createNoteOnGoToDefinitionWhenMissing` set to true, when I type a link to a new note (eg `[[new_note_x]]`) and go-to-definition, it creates the file `new_note_x.md` (which is what I want) but the title is `# new_note_x`. I would like this to be `# New Note X` instead.

(I *believe* an older version of the extension did have the behavior I want, but it seems to have changed, perhaps ~6ish months ago?)

**To Reproduce**
1. In an existing note, type a link to a missing note, like `[[new_note_x]]`.
1. Do go-to-definition on the new link (eg cmd-click).
1. Observe the new note with title `# new_note_x` instead of `# New Note X`

**Potential solution?**

I can understand why this behavior exists - it's easier to go from a human-readable title to a slugified file name than the reverse. But as is, with my link/naming conventions, when I use the workflow of typing a new link to a note and then go-to-definition to actually populated it, I end up having to do fiddly editing to de-slugify/re-humanize the note title.

The most relevant existing setting seems to be `vscodeMarkdownNotes.newNoteTemplate`. My setting is the default of `# ${noteName}`. It would be neat if there was a template option like `${humanNoteName}`, which is just `${noteName}` with `vscodeMarkdownNotes.slugifyCharacter` converted to spaces, and each word capitalized (perhaps except for stop words like "and", "the", etc).

**Comment by kortina** [comment]
I believe this is resolved.
