### ISSUE TITLE
Syntax highlighting for nested tags

### ISSUE THREAD

**Issue by me-matt** [kortina/vscode-markdown-notes#157]
**Describe the bug**
When using nested tags e.g. #tag1/tag2/tag3, only the first portion of the tag matches the syntax regex.

**Expected behavior**
I'm unsure if this is intentional behaviour, feel free to ignore if that's the case. Otherwise, I was expecting the entire tag to be highlighted.

**Screenshots**
<img width="150" alt="Screen Shot 2022-03-14 at 10 13 49 AM" src="https://user-images.githubusercontent.com/12972009/158079501-1ea6c08b-ac01-411d-8e97-43ab0a191699.png">

**Fix**
In `./syntaxes/notes.tmLanguage.json`, update `text.markdown.notes.tag` RegEx to include forward slash.

**Comment by kortina** [comment]
Resolved by 580c191e2df74f2d90e263d5a49af80b79b15a9d
