### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'rendererLog'

### ISSUE THREAD

**Issue by boozook** [kortina/vscode-markdown-notes#186]
Type: <b>Bug</b>

Many errors in log:

```log
2023-04-29 15:37:17.000 [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
```

Extension version: 0.0.26
VS Code version: Code - Insiders 1.78.0-insider (e410e7c66e7ce5c6bc31f73150d66857804a0ee9, 2023-04-28T12:48:09.032Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|. --disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kortina** [comment]
Resolved by aee655872041508efa0fc4ed1c01f89a730e24d7
