### ISSUE TITLE
would appreciate make "open references to tag" a link or a command when select the `#tag`

### ISSUE THREAD

**Issue by saleo** [kortina/vscode-markdown-notes#199]
btw, the vscodevim in recommended settings `go to reference` does NOT work

my settings are:
Markdown notes:  v0.0.27

Version: 1.85.0-insider (user setup)
Commit: 055458feab40fc308fc6d70b185068138c8cf8eb
Date: 2023-11-27T05:35:23.734Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by kortina** [comment]
You can `Peek References` for both `#tags` and `[[wiki-links]]`. 

You can `Go To Definition` for a `[[wiki-link]]` but not a `#tag`.

You can assign keyboard shortcuts for either.

<img width="744" alt="image" src="https://github.com/kortina/vscode-markdown-notes/assets/5924/9208a604-8743-458e-bf77-80c813cbc57d">

<img width="744" alt="image" src="https://github.com/kortina/vscode-markdown-notes/assets/5924/95b4a101-7cf7-4ff1-95a3-87f921dfff7e">
