### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by kolloch** [kortina/vscode-markdown-notes#24]
I couldn't find the license for this code.

A LICENSE file in the repo and/or a mention in the README.md would be great.

Thank you!

**Comment by b3u** [comment]
I agree with @kolloch that there should be a license.

@kortina If you don't have a preference, I would use the [MIT](https://choosealicense.com/licenses/mit/) or the [GNU GPL v3](https://choosealicense.com/licenses/gpl-3.0/) license. The latter doesn't allow others to distribute closed-source versions.

**Comment by kortina** [comment]
Totally, those seemed like the 2 options that looked good to me when looking at https://choosealicense.com/

I kind of lean towards the GNU GPL v3. Good to hear that is one that you think is appropriate, @b3u.

I will add a license as part of #26
