### ISSUE TITLE
Make the tag pattern customizable

### ISSUE THREAD

**Issue by Cutuchiqueno** [kortina/vscode-markdown-notes#25]
**Is your feature request related to a problem? Please describe.**
I use two other note taking apps/extensions together with this one. Both define tags in a yaml-header of the markdown file in the form of:

```
---
tags:
  - tag1
  - tag2
---
```
Unfortunately yaml parser stop working properly when a string starts with `#` and when it is not wrapped in quotation marks. But when I wrap it in quotation marks vscode-markdown-notes stops recognizing them as tags in peek/go to/reference actions - mainly because the quotation marks are considered part of the token so that is no longer a tag starting with `#`.

**Describe the solution you'd like**
A desirable solution would be make the tag pattern configurable by the user.
A simpler solution is to ignore quotation marks at the beginning and end of a token for tag parsing.

**Additional context**
The other extension/app I am working with is *Zettlr* and *VSNotes*.

**Comment by kortina** [comment]
NB: See this comment when implementing: https://github.com/kortina/vscode-markdown-notes/pull/29#issuecomment-636069137

**Comment by kortina** [comment]
I think v0.0.9 resolved this: 
![image](https://user-images.githubusercontent.com/5924/83655932-cb5e5300-a573-11ea-8ae6-5d1a6f8b04a8.png)

**Comment by subi54** [comment]
> I think v0.0.9 resolved this:
> ![image](https://user-images.githubusercontent.com/5924/83655932-cb5e5300-a573-11ea-8ae6-5d1a6f8b04a8.png)

Hi, I just started using this extension today. Been great so far. Thank you for sharing this with the community.
Tags like in your picture work and auto-complete but they do not for me otherwise. Instead of YAML headers, I usually keep them at the end of the document.

```
---

tags: #books #poetry #theNewYorkTimes
```
Is the #tag functionality limited to YAML? Or might it be some personal VSCode settings interfering with the extension?
