### ISSUE TITLE
Add document containing tips for vscode vim and workspace settings

### ISSUE THREAD

**Issue by lukesmurray** [kortina/vscode-markdown-notes#27]
**Is your feature request related to a problem? Please describe.**
Completely optional improvment. 

**Describe the solution you'd like**
Page of problems and solutions to those problems similar to the [vscode vim readme](https://github.com/VSCodeVim/Vim) or the [fzf wiki](https://github.com/junegunn/fzf/wiki/examples)

**Describe alternatives you've considered**
The blog post souping up vscode is a great start but can't be edited by the community.

**Additional context**
I can provide a PR for a separate doc. I've listed all the settings I currently use in aggregate below. I think if I were going to provide all of them I would list the problem with a heading, then the line of code as the solution. For example. As you build your very useful tool power users can provide solutions they've created on top of your tool. 

### Viewing References

This keyboard binding enables viewing the reference panel for a wiki link or tag under the cursor without using the mouse.

```json
  // vscode settings.json
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["g", "r"],
      "commands": ["references-view.find"]
    },
```

---
This is the kitchen sink of settings I use.

### VsCode Workspace Settings

```jsonc
{
  // save files after a delay automatically
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 1000,
  // sort the explorer by modified date in descending order
  "explorer.sortOrder": "modified",
  // open files as tabs
  "workbench.editor.enablePreview": false,
  // reveal existing files if they are open (avoids tons of tabs)
  "workbench.editor.revealIfOpen": true,
  // open files from quick open as tabs
  "workbench.editor.enablePreviewFromQuickOpen": false
}
```

### VsCode Vim Settings

```jsonc
    "vim.normalModeKeyBindingsNonRecursive": [
    // open references panel with gr
    {
      "before": ["g", "r"],
      "commands": ["references-view.find"]
    },
    // peek references inline with gR
    {
      "before": ["g", "R"],
      "commands": ["editor.action.referenceSearch.trigger"]
    },
    // open definition in new editor group with gs
    {
      "before": ["g", "s"],
      "commands": ["editor.action.revealDefinitionAside"]
    },
    {
      // peek definition inline with gD
      "before": ["g", "D"],
      "commands": ["editor.action.peekDefinition"]
    },
    // open link with gx
    {
      "before": ["g", "x"],
      "commands": ["editor.action.openLink"]
    }
  ],
```

**Comment by kortina** [comment]
Hey @lukesmurray this is a great idea. Been chugging away at some major refactors, but I want to add this soon.

Wondering if you have any other opinions on the README / its information hierarchy and organization?

Right now I have a ton of screenshots in there, but wondering what the best way to structure it is if we do an update.

Something like:

- short description / comps to other native apps
- table of contents
- short feature list ( + 1 animated gif screenshot? )
- essential / recommended settings
- FAQs
- Contributing

**Comment by lukesmurray** [comment]
That structure looks good to me. The extension specific settings (i.e. `workspaceFilenameConvention`) could be extracted into a table with short descriptions similar to [vscodevim's settings table](https://github.com/VSCodeVim/Vim#vscodevim-settings). The recommended workspace settings/vim settings could be provided afterwards, those are somewhat less essential.

I like the short feature list because it is concise and complete. I don't think the animated screenshots have to be removed. I personally really like the visual demonstrations. 

For the short feature list things like `new note command` are probably good as is. Short sentences with a brief tip :bulb:. Tags and Wikilinks are better to compare. For example through a table with `tag` and `wikilink` as the columns and `go to definition`, `peek definition`, `show references` as the rows. Each cell can either have ✅  🚫 , or brief descriptions like `not supported`, `creates file if doesn't exist`. Up to you.

Final bullets are

- short description
- TOC
- gifs
- short feature list
  - commands
  - comparison of tag/wikilink
- extension settings
- recommended workspace settings
  - recommended vim settings
- FAQ
- contributing

Anyway I don't want to bikeshed the readme too much. I think it's already quite good and I don't think you can go wrong.

**Comment by kortina** [comment]
@lukesmurray just doing some cleanup on this repo and wanted to close the loop on this.

I am adding your settings (really like the way you have broken it up, btw) to a new `RECOMMENDED-SETTINGS.md`.

I also recently added a separate `TROUBLESHOOTING-FAQ.md` and think these will help cleanup the main `README.md`

https://github.com/kortina/vscode-markdown-notes/commit/a360f147f6caa79b72307ccf8bbd4773e5200cb2

If you have any changes, feel free to add.
