### ISSUE TITLE
Auto complete is not working. Create new note is not working.

### ISSUE THREAD

**Issue by jay-pee** [kortina/vscode-markdown-notes#3]
Thank you for this extension! I am waiting for this kind of add on already a few month since I got into creating a Zettelkasten for my notes. Unfortunately the extension is not working properly on my PC. I think it will be quite hard to find the error but for my the autocomplete is not working and I can't create new Notes with the shortcut. Here is a small GIF that shows the problem:

![test2](https://user-images.githubusercontent.com/9380980/78457971-70f96100-76ae-11ea-85bb-a8fc25ebc337.gif)

    VS Code version: 1.43.2
    Setting python.jediEnabled: false
    OS: Windows
    Virtual environment: N/A

Maybe I do something wrong...
Tell me if you need more information to make sense of this bug.

P.S.: Also peek and look up is not working with Notes that have spaces in their name. But maybe I create a new Issue for that.

**Comment by kortina** [comment]
Can you make sure you have this in your settings (or hit your autocomplete trigger key command to see the suggestions)?

```json
  "[markdown]": {
    "editor.quickSuggestions": true
  } 
```

**Comment by jay-pee** [comment]
Thanks for your quick help. Here is the result!

![test3](https://user-images.githubusercontent.com/9380980/78458796-6e9a0580-76b4-11ea-9b34-5add486f7df1.gif)

works kind of, but there are some weird suggestions included (like "#" and "#tag")

**Comment by quickfold** [comment]
> 
> 
> Can you make sure you have this in your settings (or hit your autocomplete trigger key command to see the suggestions)?
> 
> ```json
>   "[markdown]": {
>     "editor.quickSuggestions": true
>   } 
> ```

I am trying VS code for the first time just because of this add-on, so apologies for the newbie question, but where do I put these lines in my settings?

by the way, even the link is not working for me. When I put a file in double brackets, on the preview the link goes to `http://test.md`

**Comment by flyingcroissant** [comment]
> > Can you make sure you have this in your settings (or hit your autocomplete trigger key command to see the suggestions)?
> > ```json
> >   "[markdown]": {
> >     "editor.quickSuggestions": true
> >   } 
> > ```
> 
> I am trying VS code for the first time just because of this add-on, so apologies for the newbie question, but where do I put these lines in my settings?
> 
> by the way, even the link is not working for me. When I put a file in double brackets, on the preview the link goes to `http://test.md`


I am just trying out VS Code "workspaces" myself and ended up modifying the `.code-workspace` file in that folder to be:
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"[markdown]": {
			"editor.quickSuggestions": true
		  } 
	}
}
```

The way I understand it, this setting will only apply to that workspace. You could also change it globally for VS Code by clicking the file type in the bottom right, selecting "Configure 'markdown' language-based settings" and changing it there.

**Comment by jay-pee** [comment]
> 
> 
> > Can you make sure you have this in your settings (or hit your autocomplete trigger key command to see the suggestions)?
> > ```json
> >   "[markdown]": {
> >     "editor.quickSuggestions": true
> >   } 
> > ```
> 
> I am trying VS code for the first time just because of this add-on, so apologies for the newbie question, but where do I put these lines in my settings?
> 
> by the way, even the link is not working for me. When I put a file in double brackets, on the preview the link goes to `http://test.md`

The changes are going into the settings. The settings can be modified over a UI or in a JSON file. The letter one is the way to go:

1. Open the command palette by hitting "CTRL+SHIFT+P" (On mac maybe CMD+SHIFT+P)
2. Type in settings and hit ENTER
3. Take the code snipped from the author and put it somewhere. Be careful that you use the right JSON Syntax (For example closing all brackets and using comma)

Show you a quick video here:

![tmp](https://user-images.githubusercontent.com/9380980/78533655-98087d80-77e9-11ea-9510-d0d8edd266c5.gif)

you can also put it in the workspace settings like flyingcroissant did.

**Comment by quickfold** [comment]
Thank you guys for the help! It works.
