### ISSUE TITLE
Line numbers are off

### ISSUE THREAD

**Issue by b3u** [kortina/vscode-markdown-notes#35]
FYI, *way* too long of a template, imho.

Anyways, the line numbers in the backlinks panel are consistently displayed as one number less than the actual line number. n is displayed as n-1. Cheers!

**Comment by b3u** [comment]
I'll just put this here: https://github.com/kortina/vscode-markdown-notes/blob/3145b8a7405d88097de1ddb1f72b0be73b50fe1d/src/BacklinksTreeDataProvider.ts#L171-L174

This icon doesn't exist. This will:
```js
new vscode.ThemeIcon("link")
```

**Comment by kortina** [comment]
Thanks for letting me know. Closed by #40

**Comment by kortina** [comment]
NB: I decided not to auto-complete from dirty documents, only those saved to disk. We could always add this in the future now in the `  vscode.workspace.onDidChangeTextDocument((e: vscode.TextDocumentChangeEvent) => {` https://github.com/kortina/vscode-markdown-notes/pull/40/files#diff-45327f86d4438556066de133327f4ca2R27 but I kind of figured it wasn't that crucial to get the tags before a save.
