### ISSUE TITLE
Add toggle suggestion details for link autocomplete

### ISSUE THREAD

**Issue by DrorSh** [kortina/vscode-markdown-notes#38]
Many of my notes have longer titles than presented in the autocomplete dropdown menu, making it sometimes hard to find the right file.

IntelliSense supports toggle suggestion details (toggled when clicking ctrl+spc twice) to show a detailed view of code snippets. It would be great to be able to toggle this feature on to view full titles of notes and possibly the content itself.

Since I am already here - Thank you for this incredible app!

**Comment by kortina** [comment]
Oh, this is a great idea. Anyone know the APIs you need to implement to do this?

@DrorSh can you add a screenshot of what you are talking about?

**Comment by DrorSh** [comment]
Sure

![autocomplete preview](https://user-images.githubusercontent.com/7237858/86247812-05267780-bb7b-11ea-823d-3c770618b095.png)

**Comment by kortina** [comment]
Closed by #65 in v0.0.15
