### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by rockorager** [kortina/vscode-markdown-notes#42]
_Troubleshooting: Before filing a new issue, please try to verify if this is a workspace / configuration issue, or an extension / os issue:_

- Checkout [the repo](https://github.com/kortina/vscode-markdown-notes): `git clone git@github.com:kortina/vscode-markdown-notes.git`
- Open the test notebook directory: `cd vscode-markdown-notes/test && code .`
- Open `top.md` in the test workspace in VS Code
- [No] typing `[[t`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `test.md`, `top.md`
- [No] typing `[[s`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `sub.md`, `sub2.md`
- [No] typing `#a`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `#another_tag`, `#tag`
- [Yes] typing `[[test.md]]`, moving cursor over this word,  _peekDefinition_ (`⌥F12` by default) opens Peek Definition window
- Did your bug occur in the test directory?
  - [ x] Yes
  - [ ] No 

**Describe the bug**
Auto completions not working

**To Reproduce**
- Full path to workspace directory: \Users\user\GitHub\vscode-markdown-notes\test
- Full path to file editing: test.md from test notebook

Reproduced test methods above and expected behavior doesn't happen

Fresh install of VS code, only other extension installed is Markdown All In One, behavior happens if that is disabled also

**Expected behavior**
typing '[[t' would autocomplete 

**Versions**
 - OS: windows 10
 - VS Code Version: 1.46.1
 - Extension Version: 0.0.9

**Comment by kortina** [comment]
Do you have the setting:

```
"[markdown]": {
   "editor.quickSuggestions": true
   // If you turn this on and DO NOT want suggestions
   // for non-wiki-link, non-tag words,
   // You may also want to add this setting:
   // "editor.wordBasedSuggestions": false,
}
```

Or are you using the `triggerSuggest` shortcut? You need to do one of these because markdown does not have `quickSuggestions` enabled for markdown by default. Lmk

I recently tested on fresh vscode + windows and it worked fine, so this might be your issue.

**Comment by rockorager** [comment]
Ah! Putting in that setting worked! 

Thanks
