### ISSUE TITLE
[Feature Request] Support .mdx files (configuration)

### ISSUE THREAD

**Issue by vandermerwed** [kortina/vscode-markdown-notes#44]
Hello 👋

I want to use [Foam](https://github.com/foambubble/foam) to build a Digital Garden. Part of the requirement I have is to be able to embed components in my markdown that can be rendered with [MDX](https://github.com/mdx-js/mdx).

I want to be able to change the default extension for files from `.md` to `.mdx`. This should ideally be an configuration option.

A potential alternative is to use tags like `[//component-start] ... [//component-end]` and then write a parser to extract and render these. Can possibly still use MDX, but this isn't a very clean solution.

I had a look at [NoteWorkspace.ts](https://github.com/kortina/vscode-markdown-notes/blob/3145b8a7405d88097de1ddb1f72b0be73b50fe1d/src/NoteWorkspace.ts) and it looks fairly trivial to add the configuration option to support another default file extension.

I'm happy to take a shot at implementing this. Would be amazing if someone, who is more familiar with this project, can point out anything I might be missing.

**Comment by kortina** [comment]
Closed by #40 - I was handling some other cleanup and was trivial to add support for `mdx` as a default extension. See the new config in v0.0.10

Also, tx for tipping me off to Foam -- looks like a very cool project!

Lmk if you run into other things you want to change / happy to provide guidance on the codebase / review a PR if you submit one.

**Comment by vandermerwed** [comment]
Amazing! Thanks @kortina!
