### ISSUE TITLE
[Bug] Plugin does not initialize on MDX files

### ISSUE THREAD

**Issue by vandermerwed** [kortina/vscode-markdown-notes#45]
Related to #44 

I think `noteFiles()` needs to match the new extensions as well.

```
static async noteFiles(): Promise<Array<vscode.Uri>> {
    let files = (await vscode.workspace.findFiles('**/*')).filter(
      // TODO: parameterize extensions. Add $ to end?
      (f) => f.scheme == 'file' && f.path.match(/\.(md|markdown|mdx|fountain)/i)
    );
    return files;
  }
```

I'm not sure if it might be better to have this pull from the configuration as well though...

**To Reproduce**
- Set Default File  Extension to `mdx` in VS Code settings
- Create a new page using [[New Page]] (Ctrl + hover creates a page `new-page.mdx`)
- Navigate to `new-page.mdx`
- Type [[Another Page]]
- Ctrl + hover over [[Another Page]] does nothing

**Expected behavior**
A new file with the name `another-page.mdx` should have been created

**Versions**
 - OS: Windows 10
 - VS Code Version: v1.46.1
 - Extension Version: v0.0.10

**Comment by kortina** [comment]
The `notefiles` regex matches:

```
/\.(md|markdown|mdx|fountain)/i
                              ^ here
```

I believe what is happening is that `mdx` files are not registered as part of the `markdown` language. By default, it looks like it registers at `plaintext`:

![image](https://user-images.githubusercontent.com/5924/86710857-3d411680-bfd0-11ea-9dd2-2df52b1ef32b.png)

It looks like maybe we need to register our subscriptions and providers inside the `mdx` / `text.html.markdown.jsx` https://github.com/mdx-js/vscode-mdx/blob/5aa30b41a692628018a4c289e9d7ef8956aabea1/package.json#L97

**Comment by vandermerwed** [comment]
Ah I see, didn't notice that. Can confirm that changing the language to `markdown` resolves the issue.

Thanks for looking into this.
