### ISSUE TITLE
Backlinks support for regular hyperlinks

### ISSUE THREAD

**Issue by akzaidi** [kortina/vscode-markdown-notes#46]
**Is your feature request related to a problem? Please describe.**
Local links made through simple links like `[text name](text url)` can be simpler to read than wiki links. It would be great if these were also parsed and added to backlinks.

**Describe the solution you'd like**
I'd like to see backlinks for "regular" local links, i.e.:

```markdown
# Tests

Test links:

1. [[test-wiki-link.md]]
2. [test hyperlink](test-hyperlink.md)
```

Empty for `test-hyperlink.md`:
![image](https://user-images.githubusercontent.com/1307603/86338792-9cd1a780-bc07-11ea-8720-8e3bf8bf2737.png)

But works as expected for wiki-links:
![image](https://user-images.githubusercontent.com/1307603/86338887-ba9f0c80-bc07-11ea-9b1b-0a4797cc9e66.png)

**Describe alternatives you've considered**

**Additional context**
Local links are supported for edges in [markdown-links](https://github.com/tchayen/markdown-links).

Thanks for making this extension! Using it in conjunction with `foam` and it makes me very happy!

**Comment by kortina** [comment]
This seems like a good idea. Implementation will need to:

- add parsing for regular markdown links to the reference NoteParser
- add option to completionhandler to complete as a regular link vs markdown link
- probably make both optionally because I could see the extra parsing in particular having a performance implication for large workspaces

**Comment by star191** [comment]
I want this feature so much
I think the standard links `[test hyperlink](test-hyperlink.md)` is more compatible with other MD parsers
I will use that in [foam](https://foambubble.github.io/foam/) with convenience

**Comment by tsbertalan** [comment]
I have a few existing files that all use the standard link format, and it would be nice if they were also parsed for backlinks. Somewhat off-topic, but it seems to me that the wiki-link format is more appropriate for the (default) Workspace Filename Convention of "uniqueFilenames", and regular markdown links are good for relative and absolute links. This is after all how links work, respectively, on Wikipedia and the wider internet.

**Comment by lukesmurray** [comment]
I've come up with the following convention for better interplay with markdown processors. Its pretty opinionated but I'll leave it here for ideas.

I materialize wikilinks as links by adding an extra pair of brackets and providing the link address.

`[[task inbox]]` => `[[[task inbox]]](task-inbox.md)`

This looks very ugly but it has the following properties which are nice.

- the wikilinks still exist with all their original semantics (hover, go to definition, find references). See the syntax highlighting in this pic for an example
![image](https://user-images.githubusercontent.com/34020210/89578228-d3e73a00-d7ff-11ea-8671-292f81b9d782.png)
- I can toggle the links. If you convert to plain old markdown syntax e.g. `[[task inbox]] => [task inbox](task-inbox.md)` its impossible to detect which links were originally wikilinks vs regular markdown links. If you use triple bracket syntax its trivial
- the links are rendered by common mark as `[[wikilink]]`. The double brackets may or may not be desired but they can easily be removed in post processing.

I have two commands `convert wikilinks to links` and `convert links to wikilinks` for toggling between these two syntaxes across all my notes simultaneously. 

I like the dynamic ability of wikilinks to reference notes which may or may not exist, or may exist far across the workspace so I do all my writing in wikilinks mode but just before I publish my notes I convert to this triple bracket link format. In general I don't mind the materialized link format so I usually leave things materialized unless I'm moving files around or renaming references.

**Comment by rshalaev** [comment]
+1 for this. Would be great if backlink supported Standard Markdown Links with .md extension were supported for best compatability. E.g. [link name](./file.md)

ALSO it would be really great if backlinks supported Standard Wiki Links without .md extension E.g. [[link name]] . Right now backlink only supports the following format [[link name.md]]. So we have to add .md to any links and this makes rendered text display .md extension by the link name, making rendered text /preview hard to read.

Would be happy to contribute, once I figure my way around plug-ins development.

**Comment by rshalaev** [comment]
After some additional testing looks like backlinks parser works fine on both:
Wiki Style links without `.md` extension, e.g. `[[link]]` and on
Markdown standard links `[link](link.md)`. Think the issue was caused by extension that also provided backlinks panel but was an older version. So all is working now.

**Comment by ysl970629** [comment]
@rshalaev Excuse me, could you please tell me how to check backlinks with regular markdown links `[test](test.md)` ?  That's exactly what I need.
I encountered a problem that the regular markdown link's backlink didn't show.
For example, if I link `file1.md` in `file2.md` : 
![image](https://user-images.githubusercontent.com/39717545/100530698-2f668900-3230-11eb-8625-b7a6b59d2e31.png)
```
# file2

[test](../default/file1.md)
```
And I back to `file1.md` to check if the backlink has been ceated, but It doesn't (please pay attention to the red circle in the picture's leftdown position)
![image](https://user-images.githubusercontent.com/39717545/100530642-6f793c00-322f-11eb-93af-b2ea0f68e53b.png)
