### ISSUE TITLE
Configurable template for new notes

### ISSUE THREAD

**Issue by qbikez** [kortina/vscode-markdown-notes#48]
**Is your feature request related to a problem? Please describe.**
As a user, when creating new notes, I'd like to customize how the generated markdown file looks like. 

**Describe the solution you'd like**
Have a configurable template for new notes - either as config value or a template file at well-known location.

Allow for some simple template expansion - i.e. inserting note title, current timestamp. A template may look like this:

```markdown
# ${noteName}

Created: ${timestamp}

# Tags
#tag1 #tag2
```

This should work for notes created via "New note" command and for autogenerated files.

**Describe alternatives you've considered**
Use a snippet to add content to the note, each time it is created.

**Comment by DrorSh** [comment]
This can be done almost automatically with vscode snippets. 
Use snippet-creator add-on to easily create snippets.
You can include timestamps by using variables as described here https://code.visualstudio.com/docs/editor/userdefinedsnippets

After a new note is created, just add the snippet by using the shortcut you assigned above. 
You can have different templates for different note types.

**Comment by osenvosem** [comment]
I would also suggest to add template for file names. For instance, it is a popular approach to start filenames with a timestamp which you may don't want to have in your title.

**Comment by kortina** [comment]
Closed by #49
