### ISSUE TITLE
Auto-complete works with letters but not numbers

### ISSUE THREAD

**Issue by quickfold** [kortina/vscode-markdown-notes#5]
Auto-complete matches letters but not numbers or symbols. This may be by design, but if people want to use Luhmann IDs in note titles, it will make it harder for them to find notes.

**Comment by jay-pee** [comment]
Have the same problem! I use timestamp IDs and auto-complete is not working in this note archive.

**Comment by kortina** [comment]
In wiki links, the following characters (including numbers) should work:

`regex = /\[\[[\w\.\-\_\/\\]+/i;`: 
https://github.com/kortina/vscode-markdown-notes/blob/643d384ea9537c255dec4aeccfa3824183972b8d/src/extension.ts#L74

![2020-04-11 10 38 57](https://user-images.githubusercontent.com/5924/79050779-22cdeb80-7be1-11ea-866c-ab052de4b22a.gif)

In tags, the following characters (including numbers) should work:

`regex = /\#[\w\-\_]+/i;`: https://github.com/kortina/vscode-markdown-notes/blob/643d384ea9537c255dec4aeccfa3824183972b8d/src/extension.ts#L59

![2020-04-11 10 39 45](https://user-images.githubusercontent.com/5924/79050796-3ed18d00-7be1-11ea-97e8-f08b7f0f1f94.gif)

We could potentially make these regexes configurable to allow for other symbols (such as `:`), but my inclination is to leave defaults as is.
