### ISSUE TITLE
Links containing '/' delete files

### ISSUE THREAD

**Issue by eBerdnA** [kortina/vscode-markdown-notes#50]
**Describe the bug**
Just noticed that there seems to be an issue when having links which contain '/'.

Files:
- Demo1.md
- Link-Topic.md

When `Demo1.md` does contain a link `[[Link/Topic]]` it creates a new file `link-topic.md` even though the file `Link-Topic.md` already exists. Unfortunately this does overwrite everything which has already been written in `Link-Topic.md`.

If you need any further information just let me know.

**To Reproduce**
- Full path to workspace directory: `/mnt/c/dev/foam`
- Full path to file editing: `/mnt/c/dev/foam/Demo1.md`

1. Open `Demo1.md`
2. Enter `[[Link-Topic]]`
3. Follow link
4. File `Link-Topic.md` has been recreated as `link-topic.md` and does not contain content except the header `# Link/Topic`

**Expected behavior**
Link should open existing file instead of creating a new one.

**Versions**
 - OS: WSL running Ubuntu 20.04 on Windows 10
 - VS Code Version: 1.46.1
 - Extension Version: v0.0.10

**Comment by kortina** [comment]
Hmm, good find. Shouldn't be too hard to fix this, must be some issue with the regex matcher that is looking for this file.

**Comment by kortina** [comment]
Hmm, gonna have to give this a bit more thought, since `/` is a path separator on the filesystem.

My inclination is to throw some sort of error if you try to create a new note that contains a slash character to avoid odd behavior, but let me sleep on it.

**Comment by eBerdnA** [comment]
You're right, `/` is the separator in most OS except Windows. A file name should/must not contain a `/` in any OS as far as I know. Therefore creating a file `Link-Topic.md` for a wiki-link `[[Link/Topic]]` should be the way to go.

I have created a possible fix for this issue. I narrowed this issue down to the function `normalizeNoteNameForFuzzyMatch` which calls `basename()`. As `/` is the separator this seems to me like the root cause.
But I'm not quite sure whether this fix has any side effects I didn't see.

**Comment by wgslr** [comment]
A random thought: wouldn't name capitalization play a role here as well? Linux is case sensitive, but Windows is not, so I would expect weird things to happen when searching for/creating files in WSL.

**Comment by eBerdnA** [comment]
Yes it does. But it depends not only on the operating system but also on how the file system was mounted. With a *nix operating system, a file system can also be mounted as non case sensitive.

But I think/hope my fix works in all constellations. My manual testing did work with all combinations which I have also added as unit tests in my pull request.

**Comment by kortina** [comment]
Fixed by #52
