### ISSUE TITLE
Wikilinks do not pipe |

### ISSUE THREAD

**Issue by ghost** [kortina/vscode-markdown-notes#56]
Write a note with the following: 

`this lead to his nickname, [[The Zuck|Mark Zuckerberg]].`

This should either

a) create a new note, called _Mark Zuckerberg_ **or**
b) link to an existing note, called _Mark Zuckerberg_

Instead it creates a new note _The Zuck|Mark Zuckerberg_.

See the [Wikipedia wikilink documentation](https://en.wikipedia.org/wiki/Help:Link). 
Note: I used the the [Tiddlywiki syntax](https://tiddlywiki.com/#Linking%20in%20WikiText), because I believe that it better mirrors the native markdown link mark-up: _description | link_.

**Comment by kortina** [comment]
This is a breaking change but fairly easy to implement if we decide to do it. Let me ask around and get some more opinions on it.

**Comment by lukesmurray** [comment]
If you do this I would parameterize the separator.

**Comment by kortina** [comment]
Per @lukesmurray we should probably parameterize the separator.

I think we should also parameterize the behavior all-together (eg, do we just convert "|" to a slug character or treat everything before the "|" as title.

This probably won't be too hard to implement behind a feature flag if someone wants to try a PR!
