### ISSUE TITLE
Go to reference will cause auto-complete for wiki links all the time

### ISSUE THREAD

**Issue by grainfire** [kortina/vscode-markdown-notes#58]
**IMPORTANT**

Quick suggestions are NOT enabled by default in Markdown, so to get suggestions, you have to **manually** `triggerSuggest` (`⌃Space` by default) **OR** put this in settings.json:

```
"[markdown]": {
   "editor.quickSuggestions": true
}
```

_Troubleshooting: Before filing a new issue, please try to verify if this is a workspace / configuration issue, or an extension / os issue:_

- Checkout [the repo](https://github.com/kortina/vscode-markdown-notes): `git clone git@github.com:kortina/vscode-markdown-notes.git`
- Open the test notebook directory: `cd vscode-markdown-notes/test && code .`
- Open `top.md` in the test workspace in VS Code
- [x] typing `[[t`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `test.md`, `top.md`
- [x] typing `[[s`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `sub.md`, `sub2.md`
- [x] typing `#a`,  _triggerSuggest_ (`⌃Space` by default) gives completions: `#another_tag`, `#tag`
- [x] typing `[[test.md]]`, moving cursor over this word,  _peekDefinition_ (`⌥F12` by default) opens Peek Definition window
- Did your bug occur in the test directory?
  - [x] Yes
  - [ ] No 

**Describe the bug**
Once "Go to references" (or SHIFT+F12) is used in the document, typing outside of [[]] will also invoke suggestion of note files. Restart VS Code will resolve that.

**To Reproduce**

1. Use "Go to References" anywhere in the markdown file
2. Issue will occur

**Versions**
 - OS: Windows 10
 - VS Code Version: 1.47.0
 - Extension Version: 0.0.12

**Comment by kortina** [comment]
Hmm, I am unable to reproduce this:

I triggered goto references:

![](https://s3.amazonaws.com/4rk/screen-shot-2020-07-15-20.33.44-jgda2ejs.png)

With it open I type `t` and then triggerSuggest, no suggestions.

![](https://s3.amazonaws.com/4rk/screen-shot-2020-07-15-20.34.28-c3wesajl.png)

Same if I close the panel:

![](https://s3.amazonaws.com/4rk/screen-shot-2020-07-15-20.35.24-9ghd0ppk.png)

One thing to check is whether or not you have ` "editor.wordBasedSuggestions": true,` or `false` -- this setting is not the best documented -- I think it just completes using all the words in the current document. I seem to recall having some issues with this on (which it is by default) for markdown files, and I personally have this in my settings:

https://github.com/kortina/dotfiles/blob/7ae6970f8fc87e26fabedc621df4565a1eb26d66/vscode/settings.json#L19 -

```
  "[markdown]": {
    "editor.quickSuggestions": true,
    "editor.wordBasedSuggestions": false,
    "editor.tabSize": 2
},
```

That said, even when I turned it back on, I was unable to replicate.

But maybe try setting it off for markdown files and see if that helps w your issue?
