### ISSUE TITLE
potential dataloss, overwriting notes on navigation

### ISSUE THREAD

**Issue by seanjensengrey** [kortina/vscode-markdown-notes#60]
I had a weird issue just now where when I navigated to a an existing page, the destination page would be the new page template, I could command-z and get the previous content back. And it would do this for all open tabs that the source page was referencing.

I shutdown VSCode and restarted it, instead of over writing the pages, it would display an error message when attempting to navigate, so at least the data loss stopped after the VSCode relaunch. 

![image](https://user-images.githubusercontent.com/128454/87411549-b87c6c80-c57c-11ea-94c0-4b56d499432f.png)

**Comment by kortina** [comment]
This was fixed a few days ago, you must have been on an old extension then got the update when you restarted vscode: https://github.com/kortina/vscode-markdown-notes/commit/332cb3e003c8c9201171dd16e45abe6c095cdf7a#diff-2afc05519b0e2a96007b2cf0590a842fR90
