### ISSUE TITLE
Autocomplete links and suggestions

### ISSUE THREAD

**Issue by nomad101** [kortina/vscode-markdown-notes#61]
**Is your feature request related to a problem? Please describe.**
When typing in general, I see suggestions for bold, lists etc. To turn off, I changed this code to false 
```
"[markdown]": {
        "editor.quickSuggestions": true,

```
But that also turns off the auto suggestions for completing wiki links when typing `[[`

Instead, I added your suggested code:
```
 // If you turn this on and DO NOT want suggestions
        // for non-wiki-link, non-tag words,
        // You may also want to add this setting:
        "editor.wordBasedSuggestions": false
    }
```
But that still doesn't prevent formatting suggestions popping up when typing regular text. 

Any advice will be appreciated. 

I'm new to vsc and your extension is great.

**Comment by ahazxm** [comment]
```json
"[markdown]": {
        "editor.suggest.showSnippets": false,
}
```
will turn off suggestions for bold, lists, but it will also turn off the auto suggestions for all snippets in `markdown.json`.

**Comment by kortina** [comment]
Great call, @ahazxm. I added this to the new Recommended Settings doc: https://github.com/kortina/vscode-markdown-notes/commit/a360f147f6caa79b72307ccf8bbd4773e5200cb2
