### ISSUE TITLE
[Feature Request] search or add new note

### ISSUE THREAD

**Issue by quickfold** [kortina/vscode-markdown-notes#7]
One great feature of (Roam)[http://www.roamresearch.com] is that the search bar will automatically create a new page with the search terms as a title if no page is found with that title. I would love if this could be implemented in this extension, as it makes it very fast to create new notes if your search for existing notes comes up empty. If not possible to do automatically like Roam does, maybe there could be a command to create a new note with title of currently selected text.

**Comment by kortina** [comment]
Yea, this would be sweet and I kind of wanted the *New Note* feature to work like this originally, but I'm not sure it is possible with the VS Code APIs.

If anyone has an idea on how to do this (if it is possible), please describe in the comments of this issue.

**Comment by kortina** [comment]
https://github.com/kortina/vscode-markdown-notes/releases/tag/v0.0.6 addresses this in what I think is the best way possible given the vscode APIs.

If you type a `[[wiki-l` inline in an existing notes, you will get completion items for the match. If you want to create a new note, simply complete typing the note name you want, eg, `[[wiki-link.md]]` and then use **Go To Definition** keyboard shortcut, and it will create a new note if there is not one with the name you chose.
