### ISSUE TITLE
Support to aliases for note links

### ISSUE THREAD

**Issue by denisdifazio** [kortina/vscode-markdown-notes#72]
**Describe the solution you'd like**
In Obsidian it is possible to create a alias to a `[[wiki-link]]` using the syntax `[[wiki-link|alias]]`. I think this feature is extremely helpful especially when you don't want to display the file's full name.

Example:

markdown-file.md:
`links: [[000 Index|Index]], [[010 Mind MOC|Mind]], [[Concepts MOC|Concepts]], [[020 Body MOC|Body]]`

preview:
`links: Index, Mind, Concepts, Body`

**Comment by thomaskoppelaar** [comment]
@denisdifazio this issue seems to be a duplicate of #66  and #56

**Comment by denisdifazio** [comment]
Oh sorry for that. I am closing this issue
