### ISSUE TITLE
new note not working

### ISSUE THREAD

**Issue by quickfold** [kortina/vscode-markdown-notes#8]
When I use the 'new note' function, I put in the title and nothing happens - nothing is created. I'm working in a folder in VS Code 'explorer'. Do I need to be in a workspace?

Also, why the requirement that new note titles be in Title Case caps? I prefer to enter in lower case.

**Comment by kortina** [comment]
New Note ONLY works when you are in a workspace. This behavior is expected.

There is no requirement for note titles to be Title Case. Example just shows you can enter Title Case and it will convert the filename to lower-case.
