### ISSUE TITLE
Allow autocompletion inside an empty wiki link

### ISSUE THREAD

**Issue by yamnikov-oleg** [kortina/vscode-markdown-notes#99]
**Is your feature request related to a problem? Please describe.**
I tried to autocomplete wiki links in my workspace and couldn't make it work at first. I have tried:

* Inserting an empty link `[[` and opening autocomplete options, but there were no notes there.
* Inserting a dot inside an empty link as the README gifs suggest, but couldn't actually find my notes, because VS Code thinks that the dot is part of the search query. So if I'm trying to link to `My note.md` and I type `[[.mynote]]`, the note I want doesn't match ".mynote" query because of the dot in front.

**Describe the solution you'd like**
I would like to be able to open autocomplete options inside of an empty link (`[[]]`)

**Describe alternatives you've considered**
The workaround I'm using is typing several characters of the notes name first, then opening autocompletion. For the example above I would type `[[mynote]]` then press Ctrl+Space.

**Additional context**
I have poked around the source code and have managed to accomplish what I mean with these edits: https://github.com/yamnikov-oleg/vscode-markdown-notes/commit/658c39014721fb0df8ffe5b126d209a1fa43059f

I can create a PR, but I'm not sure if that solution is correct and won't break anything.

**Comment by lucabol** [comment]
fyi I am having the same issue. I use timestamp ids as file name and nothing appears after I type [[ and invoke CTRL+SPACe.

**Comment by kortina** [comment]
@yamnikov-oleg this was always very annoying to me -- would be awesome if your change fixes it!

Do all the tests still pass w your change set?

Have you been using the forked version / have you noticed any other potential issues?

**Comment by kortina** [comment]
Closed by #122
